### ISSUE TITLE
Researching Gnome 43 errors

### ISSUE THREAD

**Issue by lukedupin** [mgalgs/gnome-shell-system-monitor-applet#27] opened 2022-11-01 16:31 UTC
The issue is related to this: https://gjs.guide/extensions/upgrading/gnome-shell-43.html#quick-settings
Specifically aggregateMenu is now gone. As a temporary fix, the battery module can be commented out since it is the only class that uses this now deleted menu. As a long term fix, it looks like the proxy code needs to be updated to handle the new "Quick" menu.

As a temporary fix, the following line can be commented out:
```
        //Main.__sm.elts.push(new Battery());
```

**Comment by mgalgs** [comment] 2022-11-01 17:31
Looks like a dupe of #25

**Closed by mgalgs** 2022-11-01 17:31 UTC
